image: golang:latest

# Setup base dependencies
before_script:
  - apt-get update && apt-get install -y unzip git
  - git config --global credential.helper '!f() { sleep 1; echo "username=${GIT_USER}"; echo "password=${GIT_PASSWORD}"; }; f'

stages:
  - deploy

# Deploy the generated code
deploy:
  stage: deploy
  script:
    - make deploy
